version: '3.8'

services:
  document-extractor-api:
    build: .
    container_name: document-extractor-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      # Mount database directory for persistence
      - ./database:/app/database
      # Mount static files for development
      - ./static:/app/static
      # Optional: Mount source code for development hot reload
      - ./src:/app/src
      - ./main.py:/app/main.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - document-extractor-network

  # Optional: Add a database service if you want to use PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:13
  #   container_name: document-extractor-db
  #   environment:
  #     POSTGRES_DB: document_extractor
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - document-extractor-network

networks:
  document-extractor-network:
    driver: bridge

# volumes:
#   postgres_data: 